### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by marketarea** [xrp-community/codius-install#3]
I tried to install many times.
I have enough money in my wallet.
Constantly the same error 502.
Though if to check up that all services are started, a firewall - ok.
Ports 7768 and 3000 are not listening.
Firewall checked several times, all ok.

**Comment by N3TC4T** [comment]
Maybe moneyd issues , run the script and enter `2` for debug  .

in the end it's shows you a path to the log file , send the log file so we can  trace the commands and services output .

Also maybe you want to remove your wallet address and balance from log file .

**Comment by N3TC4T** [comment]
I’m closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version

Thank you!
